[build]
  publish = "dist"

[[redirects]]
  from = "/chat-api/*"
  to = "https://staging.chatapi.io.vn/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
